generator:
  class: sfDoctrineGenerator
  param:
    model_class:           sfFaqCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_faq_faq
    with_doctrine_route:   true

    config:
      actions: ~
      fields:  ~
      list:
        title: Categories FAQ List
        display: [=id, name, activate]
        batch_actions: {}
      filter:  ~
      form:    ~
      edit:
        title: Edition of category "%%name%%"
        display: [created_at, name, activate]
      new:     ~
