all:
  sfDoctrineFaqPlugin:
    title:                              FAQ   # default : "FAQ", Title of page
    separator:                          '-'   # default : '|', Categories separator
    question_separator:                 '---' # default : '<hr />', Questions separator

    first_category_by_default:          true  # default : false, open the first category into load module
    first_question_by_default:          true  # default : false, open the first question into load category

    js:                                 true  # default : false, true for the FULL JS version
    close_all_question_with_category:   true  # default : false, ONLY FOR JS VERSION, close all questions when you reload a category

