sf_faq_category:
  class: sfDoctrineRouteCollection
  options:
    model:               sfFaqCategory
    module:              sfFaqAdminCategories
    prefix_path:         sfFaqAdminCategories
    column:              id
    with_wildcard_routes: true

sf_faq_faq:
  class: sfDoctrineRouteCollection
  options:
    model:               sfFaqFaq
    module:              sfFaqAdminFaq
    prefix_path:         sfFaqAdminFaq
    column:              id
    with_wildcard_routes: true

